### ISSUE TITLE
realgud:gdb overshadows comint mode bindings

### ISSUE THREAD

**Issue by MoHKale** [realgud/realgud#255]
I've found that `realgud:gdb` seems to be locally resetting my comint mode bindings with `realgud:gdb-track-mode-map`. To reproduce:
* run `emacs -q`
* navigate to a project which you can debug
* compile the project to recieve an executeable... if one doesn't exist.
* type `M-x realgud:gdb` and run it on the compiled executeable.
* run `M-x describe-bindings`
* navigate to the major mode bindings section.

For me it's been reduced to:

```
Major Mode Bindings:
key             binding
---             -------

C-c             Prefix Command

C-c !           Prefix Command
```

Is this the intended behaviour? I couldn't find any mention of this in the wiki or README and seeing as the actual major mode of the gdb buffer (as found through `M-: major-mode`) is still `comint-mode` this is actually a pretty pesky bug to hunt down.

Update: wrapping my comint bindings into a method (such that I can pass which keymap I want them bound to manually) & doing so to `realgud:gdb-track-mode-map` has restored my bindings. I still feel this qualifies as a bug, unless this is how its supposed to work? 😄.

**Comment by rocky** [comment]
> Is this the intended behaviour? 

I don't think anyone gave that much thought. And clearly the fact that this is the first time anyone has mentioned it in the 10 years the project has been around suggests it's not been that big a deal. (Perhaps part of that is because it hasn't been used as much). 

Make a suggestion of how this should work, or better put in a pull request and if it's reasonable we'll do.

**Comment by MoHKale** [comment]
Well shouldn't any minor mode normally add bindings to it's own keymap (which is then accessible while the mode is active) instead of replacing the major modes bindings with it's own map? I was under the impression that's how modes were supposed to work. though if you feel this doesn't warrant much of a change, then I'd appreciate if we could include a post in the wiki mentioning that comint binding don't work in realgud sessions (just to assist others who were as baffled as I was).

**Comment by rocky** [comment]
The wiki anyone an add to, so feel free to put something there. 

Or create its own keymap etc.

**Comment by MoHKale** [comment]
kay, I will, thnx 😄

**Comment by 813gan** [comment]
@mohkale It should be fixed by 75a6e60cd748d1687f6a6ca2b00551feff3d2edc. Could you re-check it?

**Comment by TauPan** [comment]
> @mohkale It should be fixed by [75a6e60](https://github.com/realgud/realgud/commit/75a6e60cd748d1687f6a6ca2b00551feff3d2edc). Could you re-check it?

I have that problem since upgrading to emacs 27. Before that `comint-previous-input` (M-p) and `comint-next-input` (M-n) just worked.

I can confirm that the 75a6e60 (I assume it's in 20200923.610 from melpa) does not fix this (it also seems related to the source buffer, not the pdb buffer but maybe I'm misreading it).

Confusingly, `describe-mode` still lists the comint keys:
~~~
<C-down>        comint-next-input
<C-up>          comint-previous-input
[...]
M-n             comint-next-input
M-p             comint-previous-input
~~~

**Comment by TauPan** [comment]
> Update: wrapping my comint bindings into a method (such that I can pass which keymap I want them bound to manually) & doing so to `realgud:gdb-track-mode-map` has restored my bindings. I still feel this qualifies as a bug, unless this is how its supposed to work? .

I'm not clear on how to accomplish that.

[...]

> The wiki anyone an add to, so feel free to put something there.

> Or create its own keymap etc.

[...]

> kay, I will, thnx smile

I don't see anything in the wiki either.

**Comment by mohkale** [comment]
Whoops @TauPan, I installed realgud but then promptly never ended up using it so this issue kind of slipped my mind.

Here's what I meant:

```
(defun +comint-set-bindings (keymap)
  ;; abstracted into a method because realgud seems
  ;; to hide all of these bindings.
  (general-define-key
   :keymaps keymap
   "RET" 'comint-send-input
   "M-RET" 'comint-accumulate))

(with-eval-after-load 'comint
  (+comint-set-bindings 'comint-mode-map))

(with-eval-after-load 'realgud
  (+comint-set-bindings 'realgud:gdb-track-mode-map))
```

**Comment by TauPan** [comment]
Hm... I was wondering why it used to work and I'm one of those guys who update emacs packages very infrequently.

I found the following commit to be relevant: https://github.com/realgud/realgud/commit/62f7eb57b3b1a71f7f0079fc97fcb105b0f65fe6

In fact I see that it makes sense to use `shell-mode-map` in bashdb, but I don't see why this would be useful in other debuggers.

So it looks like I was using an over 6 year old version of realgud for a very long time and updated after the emacs 27 update (possibly because of other issues).

Not sure how to properly fix this, since I'm not using bashdb at all.

**Comment by TauPan** [comment]
> I found the following commit to be relevant: [62f7eb5](https://github.com/realgud/realgud/commit/62f7eb57b3b1a71f7f0079fc97fcb105b0f65fe6)

Nah, reverting this locally doesn't help. What also doesn't help is to copy the realgud-track-mode-map in the local track-mode-maps via `realgud-track-mode-vars`. I really have no idea. :man_shrugging:

**Comment by TauPan** [comment]
> Whoops @TauPan, I installed realgud but then promptly never ended up using it so this issue kind of slipped my mind.
> 
> Here's what I meant:
> 
> ```
> (defun +comint-set-bindings (keymap)
>   ;; abstracted into a method because realgud seems
>   ;; to hide all of these bindings.
>   (general-define-key
>    :keymaps keymap
>    "RET" 'comint-send-input
>    "M-RET" 'comint-accumulate))
> 
> (with-eval-after-load 'comint
>   (+comint-set-bindings 'comint-mode-map))
> 
> (with-eval-after-load 'realgud
>   (+comint-set-bindings 'realgud:gdb-track-mode-map))
> ```

For my use-case (pdb) the following works:
```emacs-lisp
(defun +comint-set-bindings (keymap)
                 ;; abstracted into a method because realgud seems
                 ;; to hide all of these bindings.
                 (bind-key "M-p" #'comint-previous-input keymap)
                 (bind-key "M-n" #'comint-next-input keymap))
(with-eval-after-load 'realgud
                 (+comint-set-bindings realgud-track-mode-map)
                 (+comint-set-bindings realgud-backtrace-mode-map))
```
